version: '3.6'

services:

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - defaultnet

  zhaw-issue-tracker-server:
    image: zhaw-issue-tracker-server:latest
    depends_on:
      - mongo
    ports:
      - 3000:3000
    networks:
      - defaultnet

volumes:
  mongo_data:

networks:
  defaultnet: